/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: sgx-linux-x86_64"
#define DATE "built on: Mon Mar  8 12:02:35 2021 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','f',
    'P','I','C',' ','-','p','t','h','r','e','a','d',' ','-','m','6',
    '4',' ','-','W','a',',','-','-','n','o','e','x','e','c','s','t',
    'a','c','k',' ','-','W','a','l','l',' ','-','O','3',' ','-','g',
    ' ','-','i','n','c','l','u','d','e','/','h','o','m','e','/','s',
    'r','i','/','T','h','e','s','i','s','/','M','a','s','t','e','r',
    '-','T','h','e','s','i','s','/','S','G','X','D','a','t','a','C',
    'e','n','t','e','r','A','t','t','e','s','t','a','t','i','o','n',
    'P','r','i','m','i','t','i','v','e','s','/','Q','u','o','t','e',
    'V','e','r','i','f','i','c','a','t','i','o','n','/','s','g','x',
    's','s','l','/','L','i','n','u','x','/','.','.','/','o','p','e',
    'n','s','s','l','_','s','o','u','r','c','e','/','b','y','p','a',
    's','s','_','t','o','_','s','g','x','s','s','l','.','h',' ','-',
    'D','O','P','E','N','S','S','L','_','U','S','E','_','N','O','D',
    'E','L','E','T','E',' ','-','D','L','_','E','N','D','I','A','N',
    ' ','-','D','O','P','E','N','S','S','L','_','P','I','C',' ','-',
    'D','O','P','E','N','S','S','L','_','C','P','U','I','D','_','O',
    'B','J',' ','-','D','O','P','E','N','S','S','L','_','I','A','3',
    '2','_','S','S','E','2',' ','-','D','O','P','E','N','S','S','L',
    '_','B','N','_','A','S','M','_','M','O','N','T',' ','-','D','O',
    'P','E','N','S','S','L','_','B','N','_','A','S','M','_','M','O',
    'N','T','5',' ','-','D','O','P','E','N','S','S','L','_','B','N',
    '_','A','S','M','_','G','F','2','m',' ','-','D','S','H','A','1',
    '_','A','S','M',' ','-','D','S','H','A','2','5','6','_','A','S',
    'M',' ','-','D','S','H','A','5','1','2','_','A','S','M',' ','-',
    'D','K','E','C','C','A','K','1','6','0','0','_','A','S','M',' ',
    '-','D','R','C','4','_','A','S','M',' ','-','D','M','D','5','_',
    'A','S','M',' ','-','D','A','E','S','N','I','_','A','S','M',' ',
    '-','D','V','P','A','E','S','_','A','S','M',' ','-','D','G','H',
    'A','S','H','_','A','S','M',' ','-','D','E','C','P','_','N','I',
    'S','T','Z','2','5','6','_','A','S','M',' ','-','D','X','2','5',
    '5','1','9','_','A','S','M',' ','-','D','P','O','L','Y','1','3',
    '0','5','_','A','S','M',' ','-','D','N','D','E','B','U','G',' ',
    '-','D','_','F','O','R','T','I','F','Y','_','S','O','U','R','C',
    'E','=','2',' ','-','D','G','E','T','P','I','D','_','I','S','_',
    'M','E','A','N','I','N','G','L','E','S','S','\0'
};
